name: Update Offline Docs

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout theos/theos
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'

      - name: Checkout theos/theos.dev
        uses: actions/checkout@v3
        with:
          repository: theos/theos.dev
          path: tmp
          submodules: recursive
          fetch-depth: 1

      - name: Build docs
        run: |
          make -C tmp all
          mkdir -pv docs/assets/
          cp -av tmp/_site/docs/* docs/
          cp -av tmp/_site/assets/*.css docs/assets/
          rm -rvf tmp

      - name: Cleanup broken formatting
        run: |
          # "/assets/" is only used for stylesheet in offline docs, so make simple "assets/"
          sed -i 's/href="\/assets\//href="assets\//g' docs/*.html

          # "/" is for the site root, which we don't copy, so ignore "#"
          sed -i 's/<a href="\/">/<a href="#">/g' docs/*.html

          # "/docs/" is for the docs root which is "./docs/index.html" since need relative links
          sed -i 's/<a href="\/docs\/">Home<\/a>/<a href="\/docs\/index.html">Home<\/a>/g' docs/*.html

          # need to mask http "/docs/" links so we can modify for "/docs/*.html"
          sed -i 's/href="https:\/\/theos.dev\/docs\//href="https:\/\/mask/g' docs/*.html

          # the actual modification target "/docs/" to "./"
          sed -i 's/href="\/docs\//href=".\//g' docs/*.html

          # undoing the http masking mentioned above
          sed -i 's/href="https:\/\/mask/href="https:\/\/theos.dev\/docs\//g' docs/*.html

          # this is local, so not deployed anywhere
          sed -i 's/ Deployed on <a href="https:\/\/netlify.com">Netlify<\/a>.//g' docs/*.html

      - name: Update docs
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add docs
          git commit -m "[docs] Update offline docs to the latest commit" && git push || echo "No changes were made"
