name: Update-Submodules

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.UPDATE_SUBMODULES_TOKEN }}

      - name: Update submodules
        run: |
          git config --global user.name 'PoomSmart'
          git config --global user.email 'poomsmart@users.noreply.github.com'
          git submodule update --remote --init --recursive
          git commit --all -m "[submodules] Update submodules to the latest commit"
          git push origin master
